format_version: v1.0
type: UniqueComponent
attributes: {id: hemc}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: CS_0_COMMENT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: 'false'}
  - type: String
    attributes: {id: CS_0_END_ADDRESS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '0x5fffffff'}
  - type: Boolean
    attributes: {id: CS_0_HECC_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: KeyValueSet
    attributes: {id: CS_0_MEMORY_BANK_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '9'}
  - type: Hex
    attributes: {id: CS_0_MEMORY_BASE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '0'}
  - type: Boolean
    attributes: {id: CS_0_RAM_CHECK_BIT_INIT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Hex
    attributes: {id: CS_0_RAM_CHECK_BIT_INIT_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '0'}
  - type: String
    attributes: {id: CS_0_START_ADDRESS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0x60000000'}
  - type: Boolean
    attributes: {id: CS_1_COMMENT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: 'false'}
  - type: String
    attributes: {id: CS_1_END_ADDRESS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '0x6017ffff'}
  - type: Boolean
    attributes: {id: CS_1_HECC_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: CS_1_MEMORY_BANK_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '6'}
  - type: Hex
    attributes: {id: CS_1_MEMORY_BASE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '64'}
  - type: Boolean
    attributes: {id: CS_1_RAM_CHECK_BIT_INIT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Hex
    attributes: {id: CS_1_RAM_CHECK_BIT_INIT_SIZE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '524288'}
      - type: User
        attributes: {value: '419424'}
  - type: String
    attributes: {id: CS_1_START_ADDRESS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0x60100000'}
  - type: Boolean
    attributes: {id: HECC_INJECTION_TEST_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: HECC_INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Comment
    attributes: {id: HEMC_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** HEMC is running at 25000000 Hz ****'}
  - type: Comment
    attributes: {id: HEMC_HECC_INTERRUPT_ENABLE_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: HSMC_CHIP_SELECT1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: HSMC_DATA_BUS_CS0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '2'}
  - type: KeyValueSet
    attributes: {id: HSMC_DATA_BUS_CS1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '2'}
      - type: User
        attributes: {value: '0'}
  - type: Integer
    attributes: {id: HSMC_NCS_RD_PULSE_CS1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '6'}
  - type: Integer
    attributes: {id: HSMC_NCS_RD_SETUP_CS1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Integer
    attributes: {id: HSMC_NCS_WR_PULSE_CS1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '6'}
  - type: Integer
    attributes: {id: HSMC_NCS_WR_SETUP_CS1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Integer
    attributes: {id: HSMC_NRD_CYCLE_CS1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '10'}
  - type: Integer
    attributes: {id: HSMC_NRD_PULSE_CS1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '6'}
  - type: Integer
    attributes: {id: HSMC_NRD_SETUP_CS1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: KeyValueSet
    attributes: {id: HSMC_NWAIT_MODE_CS0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '0'}
  - type: KeyValueSet
    attributes: {id: HSMC_NWAIT_MODE_CS1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: hemc, value: '0'}
  - type: Integer
    attributes: {id: HSMC_NWE_CYCLE_CS1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '10'}
  - type: Integer
    attributes: {id: HSMC_NWE_PULSE_CS1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '6'}
  - type: Integer
    attributes: {id: HSMC_NWE_SETUP_CS1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Boolean
    attributes: {id: HSMC_READ_ENABLE_MODE_CS1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: HSMC_WRITE_ENABLE_MODE_CS1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
- type: ElementPosition
  attributes: {x: '307', y: '79', id: hemc}
